project:
  type: website
  output-dir: docs  # Carpeta donde se guardará el sitio renderizado (para GitHub Pages)

website:
  title: "Mi sitio"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: about.qmd
        text: Sobre mí
      - href: projects.qmd
        text: Proyectos
      - icon: github
        href: "https://github.com/Brandon780"
        aria-label: GitHub
      - icon: linkedin
        href: "https://www.linkedin.com/in/brandonth/"
        aria-label: LinkedIn
  page-footer:
    center:
      - text: "Sitio creado por Brandon • 2025"

format:
  html:
    theme: flatly
    css: css/styles.css
    toc: true
    code-fold: true
    code-summary: "Ver código"

editor: visual

execute:
  freeze: auto
