project:
  type: website
  output-dir: docs  # Carpeta donde se guardará el sitio renderizado (para GitHub Pages)

website:
  title: "Mi sitio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    toc: true




